import = [
    "~/.config/alacritty/themes/themes/mariana.toml"
]


colors.draw_bold_text_with_bright_colors = true
window.opacity = 0.95
window.dynamic_title = true
live_config_reload = true
window.option_as_alt="Both"

[window.padding]
x = 5
y = 5

[window.dimensions]
columns =  180
lines =  40 

[scrolling]
history = 100_000
multiplier = 3

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"


[bell]
animation = "EaseOutExpo"
duration = 0
color = "0xffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"
unfocused_hollow = true

[shell]
program = "/bin/zsh"
args = [ "--login" ]

[[hints.enabled]]
regex = '(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+'
command = "open"
post_processing = true

[hints.enabled.mouse]
enabled = true
mods = "Control"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Left", mods = "Super", chars= "\u0001"},
  { key = "Right", mods = "Command", chars= "\u0005" }
]
