colors.draw_bold_text_with_bright_colors = true
window.opacity = 0.85
window.dynamic_title = true
live_config_reload = true

[window.padding]
x = 10
y = 10

[scrolling]
history = 100_000
multiplier = 3

[font]
size = 12

  [font.normal]
  family = "Monaco"
  style = "Regular"

  [font.bold]
  family = "Menlo"
  style = "Bold"

  [font.italic]
  family = "Menlo"
  style = "Italic"

  [font.bold_italic]
  family = "Menlo"
  style = "Bold Italic"

[colors.primary]
background = "0x181818"
foreground = "0xd8d8d8"

[colors.cursor]
text = "0x181818"
cursor = "0xd8d8d8"

[colors.normal]
black = "0x181818"
red = "0xab4642"
green = "0xa1b56c"
yellow = "0xf7ca88"
blue = "0x7cafc2"
magenta = "0xba8baf"
cyan = "0x86c1b9"
white = "0xd8d8d8"

[colors.bright]
black = "0x585858"
red = "0xab4642"
green = "0xa1b56c"
yellow = "0xf7ca88"
blue = "0x7cafc2"
magenta = "0xba8baf"
cyan = "0x86c1b9"
white = "0xf8f8f8"

[[colors.indexed_colors]]
index = 16
color = "0xdc9656"

[[colors.indexed_colors]]
index = 17
color = "0xa16946"

[[colors.indexed_colors]]
index = 18
color = "0x282828"

[[colors.indexed_colors]]
index = 19
color = "0x383838"

[[colors.indexed_colors]]
index = 20
color = "0xb8b8b8"

[[colors.indexed_colors]]
index = 21
color = "0xe8e8e8"

[bell]
animation = "EaseOutExpo"
duration = 300
color = "0xffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"
unfocused_hollow = true

[shell]
program = "/bin/zsh"
args = [ "--login" ]

[[hints.enabled]]
regex = '(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+'
command = "open"
post_processing = true

  [hints.enabled.mouse]
  enabled = true
  mods = "Control"
